### PR TITLE
twig pagination function

### PR DESCRIPTION
**Pull request by gigago**
Adds twig function paginate($collection, $limit, $ignore_url_params) to paginate arbitrary collections, e.g. list items. A working example can be seen at http://ami-web.nl/events

$collection - the collection
$limit - max # of items per page
$ignore_url_params - set to true if page parameters cause trouble (default false). In this case one may need to handle url parameters manually.

### CODE REVIEW

**Comment by Sogl** [comment]
nice :+1:

**Comment by Sogl** [comment]
@rhukster ping :wink:

**Comment by gigago** [comment]
Any action or comments on this?

**Comment by flaviocopes** [comment]
Can you provide an example of how you use it in your Twig? Thanks

**Comment by gigago** [comment]
Sure, you're welcome. I'll try to represent the most generic part of the code while offering some application context as well. In this example, it's used to paginate an ordered collection of child pages, which appear as summaries in a sidebar. Since unrelated url parameters may appear which may not correspond, url params are to be ignored. This specific application has a paginated sidebar and an active item display, to which at all times the sidebar must be synchronized (ie, never show a page which does not contain the active item). It looks like [this](http://ami-web.nl/events/page:2/event:gasselforsale).

`
{% set ignore_url_params = true %}
{% set collection = page.find('/events/_events').children %}

{# In my application, here's some surprisingly complex application specific stuff - including redirects - to make url parameters behave nicely and synchronize between the sidebar and the active item display. The url may contain either (sidebar) page or active item parameters, both or none. All of this is very much optional and depends entirely on your specific needs. #}

{% do paginate(collection, limit, ignore_url_params) %}
`

After this, it's a matter of looping over the paginated collection to create a presentation as wished. If you need any more information, don't hesitate to ask. It's my pleasure.

**Comment by gigago** [comment]
Sure, you're welcome. * Previous rambling story deleted, this version is more to the point. *

### The short

```
{% set collection = << your favourite collection >> %}
{% set limit = << What... is your favourite number? >> %}
{# by default, ignore_url_params == false #}

{% do paginate(collection, limit) %}
```

This will paginate the collection, creating a pagination bar with links including the original url parameters.

### The long

In [this example](http://ami-web.nl/events/page:2/event:gasselforsale), it's used to paginate an ordered collection of child pages, which appear as summaries in a sidebar. This specific modular page has a paginated sidebar with an item list, and a separate active item display, to which at all times the sidebar must be synchronized (ie, never show a sidebar page which does not contain the active item).

Since in this application url parameters may mismatch, be mutually inconsistent or be unrelated, url params are to be ignored by the pagination plugin. The effect is, that they do not show up in the pagination bar links. Correct url parameters are passed via the links in the sidebar.

```
{% set collection = page.find('/events/_events').children %}
{% set ignore_url_params = true %}

{% do paginate(collection, limit, ignore_url_params) %}
````

After this, it's a matter of iterating over the paginated collection to create a presentation as needed. The pagination bar contains links to the different pages, nothing special here except for omitted url parameters. By default, the example page displays the first item of a sidebar page if it receives only a page parameter.

- The main point of the plugin twig extension is to be able to pick a random collection and paginate it.
- The point of ignoring the url parameters is to remove url parameters from the pagination bar, preventing conflicts where other url parameters are involved.

If you need any more information, don't hesitate to ask. It's my pleasure.

**Comment by gigago** [comment]
Latest commit adds url param array, fixes broken default argument and removes unnecessary yaml property.

The argument _$ignore_url_params_ has been removed. Instead, the optional argument _$ignore_url_param_array_ can be given a list of url parameters to ignore.

### Basic usage

```
{% set collection = << your favourite collection >> %}
{% set limit = << your favourite number >> %}
{% do paginate(collection, limit) %}
```
This creates a paginated collection with << limit >> items per page.

### Extended usage

```
{% set collection = page.find('/other/_events').children %}
{% set limit = 5 %}
{% do paginate(collection, limit, ['event']) %}
```

Above example is taken from [this website](http://ami-web.nl/events/page:2/event:gasselforsale). This code creates a paginated collection with 5 items per page. The url parameter 'event' is filtered out, so it does not show up in the pagination bar's links, preventing inconsistencies with the page parameter.

**Comment by gigago** [comment]
Sorry for having trouble making my mind up here, resulting in some superfluous and wordy comments. With the recent functional change the code is both more flexible and easier to explain. I expect no further need for changes in this area.

**Comment by gigago** [comment]
OK - at this time I have both pagination scenarios tested, via twig and via _onCollectionProcessed_ event. Both should work without errors now * ahem *.

**Comment by gigago** [comment]
# Twig pagination function

## Creating the paginated collection

**Basic usage**

{% set collection = << some collection >> %}
{% set limit = << number of items per page >> %}
{% do paginate( collection, limit ) %}
This creates a paginated collection with << limit >> items per page. As usual, any url parameters - except the page parameter, which is recreated - are passed on to the pagination bar's links.

**Extended usage**

{% set collection = page.find( '/other/_events' ).children %}
{% set limit = 5 %}
{% set ignore_url_param_array = [ 'event' ] %}
{% do paginate( collection, limit, ignore_url_param_array ) %}

The above example is taken from this website. This code creates a paginated collection with 5 items per page (the event summary list) which is presented together with an active event. The active event appears in only one of the summary pages. Consequently, the url parameter 'event' should be filtered out so it does not show up in the pagination bar's links, preventing inconsistencies with different page parameters. Any non listed url parameters (except the page parameter) are passed through unaffected. The requested page contains logic to pick a sensible default event.

## Rendering the paginated collection

The rest is in fact completely identical to the standard procedure.

{# create list of items #}
{% for item in collection %}
   ...
{% endfor %}

{# include the pagination bar #}
{% if config.plugins.pagination.enabled and collection.params.pagination %}
    {% include 'partials/pagination.html.twig' with {'base_url':page.url, 'pagination':collection.params.pagination} %}
{% endif %}

**Comment by Sogl** [comment]
@flaviocopes Any changes on this? I'm still waiting because it needed in my project.

**Comment by gigago** [comment]
As far as I'm concerned this is finished. Please let me know if there's any questions or actions I need to take to finalize this PR.

**Comment by rhukster** [comment]
Would you mind adding your Twig pagination help/guide to the README?  After that is done, i'll merge this PR.

Thanks!

**Comment by gigago** [comment]
Done. Thank you!

**Comment by Sogl** [comment]
@gigago Something strange with your markdown:
https://github.com/getgrav/grav-plugin-pagination/pull/22/commits/e0dabd3c4b8b7cd08cd6d642d83f0c4e90144672?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

Remove `+` sign first.

**Comment by Sogl** [comment]
@gigago Previous link show your changes, it's ok.
That's how it looks finally:
https://github.com/gigago/grav-plugin-pagination/blob/14dd65d9b5299e494e85ee5a205e255c5e016f06/README.md

**Comment by gigago** [comment]
Ok, thanks. Apparently empty lines are needed around the code blocks.

**Comment by Sogl** [comment]
You can also enable highlighting for your code adding ```twig.

Before:
```
{% set collection = page.find( '/other/_events' ).children %}
{% set limit = 5 %}
```

After:
```twig
{% set collection = page.find( '/other/_events' ).children %}
{% set limit = 5 %}
```

**Comment by gigago** [comment]
Cool, thanks a lot!

**Comment by rhukster** [comment]
Thanks for this handy improvement!

**Comment by gigago** [comment]
You're more than welcome! Thanks for an awesome platform!

**Pull request merged**
